"""
Django settings for carblog project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w8u9kg$5f8lv)@-ec=fuoorerjk@c@w#x#$s+vtxr0nnzelp=n'
# для разработки нижнюю строку закоммент, верхнюю разкоммент.
# SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'w8u9kg$5f8lv)@-ec=fuoorerjk@c@w#x#$s+vtxr0nnzelp=n')
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# для разработки нижнюю строку закоммент, верхнюю разкоммент.
DEBUG = bool( os.environ.get('DJANGO_DEBUG', True) )

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'markupsafe',
    'blog_engine',
    'tinymce',
    'treebeard',
    'parler',
    'sorl.thumbnail',
    'rosetta',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'carblog.urls'

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

TEMPLATES = [
    # {
    #     'BACKEND': 'django.template.backends.jinja2.Jinja2',
    #     'DIRS': ['%s/blog_engine/jinjatemplates/'% (PROJECT_DIR),
    #              os.path.join(BASE_DIR, "jinjatemplates")],
    #     'APP_DIRS': True,
    #     'OPTIONS': {
    #         'environment': 'blog_engine.myjinja2.JinjaEnvironment'
    #     }
    # },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'blog_engine/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_CONTEXT_PROCESSORS = 'django.core.context_processors.request'

WSGI_APPLICATION = 'carblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# настройки мультиязычности сайта
# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = (
    ('en', _('English')),
    ('ru', _('Russian')),
    ('uk', _('Ukraine')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

# настройки django-parler
PARLER_LANGUAGES = {
    None: (
        {'code': 'en'},
        {'code': 'ru'},
        {'code': 'uk'},
    ),
    'default': {
        'fallback': 'en',
        'hide_untranslated': False, # не скрывать то, что перевести не удалось
    }
}

# настройка для кеширования

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "d:/rve_work/carblog_cache/",
    }
}

#end настройка для кеширования

# end настройки мультиязычности сайта

# настройки django rest framework

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# end настройки django rest framework


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = '/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'blog_engine/files')
MEDIA_URL = '/blog_engine/files/'

# настройки для отправки почты
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = "paradoxtestsoft@gmail.com"
EMAIL_HOST_PASSWORD = "testingprogram"
EMAIL_USE_TLS = True
SERVER_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# конец настроек для отправки почты

# настройки celery + redis
# Celery application definition
# BROKER_URL = 'redis://localhost:6379'
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# # CELERY_RESULT_SERIALIZER = 'json'
# # CELERY_TASK_SERIALIZER = 'json'
# BROKER_BACKEND="redis"
# end настройки celery + redis



# djcelery.setup_loader()

# BROKER_HOST = "localhost"
# BROKER_BACKEND="redis"
# REDIS_PORT=6379
# REDIS_HOST = "localhost"
# BROKER_USER = ""
# BROKER_PASSWORD =""
# BROKER_VHOST = "0"
# REDIS_DB = 0
# REDIS_CONNECT_RETRY = True
# CELERY_SEND_EVENTS=True
# CELERY_RESULT_BACKEND='redis'
# CELERY_TASK_RESULT_EXPIRES =  10
# CELERYBEAT_SCHEDULER="djcelery.schedulers.DatabaseScheduler"
# CELERY_ALWAYS_EAGER=False

# Celery settings
# # Время, через которое хранимый в результат будет удалён: 5 часов
# CELERY_TASK_RESULT_EXPIRES = 18000
# # Отправлять оповещение о проблемах выполнения тасков на E-mail (берутся адреса из settings.ADMINS)
# CELERND_TASK_ERROR_EMAILS = True
# # Тип бекенда Celery для хранения результатов выполнения заданий
# CELERY_RESULT_BACKEND = "redis"
# # Адрес Redis-сервера
# CELERY_REDIS_HOST = "localhost"
# # Порт Redis-сервера
# CELERY_REDIS_PORT = 6379
# # Нормер Redis Database
# CELERY_REDIS_DB = 0

# Broker settings
# Адрес броекра. Мы указываем протокол (redis://), адрес сервера (localost), порт (6379) и номер БД (0)
# BROKER_URL = "redis://localhost:6379/0"
# CELERY_BROKER_URL = 'redis://localhost'

# это была попытка использовать rabbitmq
CELERY_BROKER_URL = 'amqp://localhost'

# BROKER_HOST = "localhost"
# BROKER_PORT = 5672
# BROKER_USER = "paradox"
# BROKER_PASSWORD = "paradox"
# BROKER_VHOST = "paradox_host"
BROKER_URL = 'amqp://paradox:paradox@localhost:5672/paradox_host'
# SITE_ID = 1

# Activate Django-Heroku.
django_heroku.settings(locals())


