# Generated by Django 2.0.7 on 2018-07-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0003_auto_20180730_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Write your name of article', max_length=250),
        ),
    ]
