# Generated by Django 2.1 on 2018-08-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0014_auto_20180823_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='next',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='prev',
        ),
        migrations.AddField(
            model_name='comment',
            name='child_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='com_children', to='blog_engine.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_parent', to='blog_engine.Comment'),
        ),
        migrations.AlterField(
            model_name='category',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='category_article', to='blog_engine.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Write your commentary here', max_length=1024),
        ),
    ]
