# Generated by Django 2.1 on 2018-08-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0016_auto_20180827_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='children_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_child', to='blog_engine.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_parent', to='blog_engine.Category'),
        ),
    ]
