# Generated by Django 2.1 on 2018-08-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0020_treecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tree_category',
            field=models.ManyToManyField(to='blog_engine.TreeCategory'),
        ),
    ]
