# Generated by Django 2.1 on 2018-08-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0022_auto_20180829_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog_engine.Article'),
        ),
    ]
