# Generated by Django 2.1 on 2018-09-03 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0024_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Write your name of article', max_length=250, verbose_name='Title')),
                ('description', models.CharField(help_text='Enter a little description of your article', max_length=1000, verbose_name='Description')),
                ('body', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'article Translation',
                'db_table': 'blog_engine_article_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='article',
        ),
        migrations.RemoveField(
            model_name='category',
            name='children_category',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, help_text='Enter the author of article', on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_updating',
            field=models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='Date of updating'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/articles', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='tree_category',
            field=models.ManyToManyField(related_name='Category', to='blog_engine.TreeCategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog_engine.Article'),
        ),
        migrations.AlterUniqueTogether(
            name='articletranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
