# Generated by Django 2.1 on 2018-09-18 09:15

import blog_engine.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0025_auto_20180903_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Article Translation'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_creation', 'author', 'article'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id'], 'verbose_name': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['blogger', 'subscriber'], 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='treecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image of your article', upload_to=blog_engine.models.unique_name_and_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tree_category',
            field=models.ManyToManyField(help_text='Select categories', related_name='Category', to='blog_engine.TreeCategory'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='body',
            field=tinymce.models.HTMLField(help_text='Write text of article here', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog_engine.Article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_updating',
            field=models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Write your commentary here', max_length=1024, verbose_name='Text of comment'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subscriber',
            field=models.EmailField(max_length=254, verbose_name='Email of subscriber'),
        ),
        migrations.AlterField(
            model_name='treecategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name of category'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog_engine.models.avatar_name_and_path, verbose_name='Avatar'),
        ),
    ]
